### ISSUE TITLE
token detection in DNS

### ISSUE THREAD

**Issue by PAStheLoD** [antoiner77/letsencrypt.sh-pdns#1]
Hello!

I'd like to suggest making two edits to this:
`while ! dig @8.8.8.8 -t TXT _acme-challenge.$domain | grep "$token" > /dev/null`

first, use +trace and +short instead of 8.8.8.8, because 8.8.8.8 caches stuff,
and use `grep -- "$token"`, because the tokens sometimes start with `-`.

**Comment by antoinerrr** [comment]
Hi,
Thanks good idea !
