### ISSUE TITLE
Add optional config file

### ISSUE THREAD

**Issue by siliconalchemy** [antoiner77/letsencrypt.sh-pdns#12]
Mysql values hardcoded into script, would be nice to be able to have a config file holding these values instead of hacking script.

**Comment by siliconalchemy** [comment]
pdns.sh.conf should just contain the same values, but can be altered here instead of hacking script:

```
mysql_base="pdns"
mysql_host="localhost"
mysql_user="root"
mysql_pass="password"
table_domains="domains"
table_records="records"
```

**Comment by antoinerrr** [comment]
Check your inbox, since i can't work on this script now, feel free to push :)

**Comment by siliconalchemy** [comment]
Great thanks, branching/PRs is overloading my brain :)
